server:
  port: 8080
spring:
  h2:
    console.enabled: true
    datasource:
      url: 'jdbc:h2:mem:'
      username: sa
      password: root
      driverClassName: org.h2.Driver
      initialize: false
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
